export default {
    CREATE: 'CREATE',
    CREATE_FAIL: 'CREATE_FAIL',
    DELETE: 'DELETE',
    DELETE_FAIL: 'DELETE_FAIL',
    UPDATE: 'UPDATE',
    UPDATE_FAIL: 'UPDATE_FAIL',
    GET:'GET',
    GET_FAIL: 'GET_FAIL',
    SET_LOADING: 'SET_LOADING'
}